# application config
server:
  port: ${SERVER_PORT:8121}
  servlet:
    context-path: ${CONTEXT_PATH:/activity/command/api}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:bc4d8b7edec8b8d89580ee0fbc008e2ee85c57bf2d099927207b3a3e8af0e044}

  # hibernate config
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      naming:
        physical-strategy: ${HIBERNATE_NAMING:org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}

  # datasource config
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/ActivityCommandService}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:12345678}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}

# cloudinary
cloudinary:
  cloudName: ${CLOUDINARY_NAME:dzd9sonxs}
  apiKey: ${CLOUDINARY_API_KEY:979314734532517}
  apiSecret: ${CLOUDINARY_API_SECRET:DCGohkxvvu85jQcSiXp_thMzTsw}
  secure: ${CLOUDINARY_SECURE:true}

logging:
  level:
    root: debug